# .yaml config file
#
# The PID gains and controller settings must be saved in a yaml file that gets loaded
# to the param server via the roslaunch file (moving_cube_control.launch).

cart_pole_3d:
  # Publish all joint states -----------------------------------
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 30
  # Effort Controllers ---------------------------------------
  pole_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: cart_pole_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}

  # Effort Controllers ---------------------------------------
  cart_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: base_cart_joint
    pid: {p: 100.0, i: 0.0, d: 0.0}
